---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
library(tidyverse)
library(targets)
tar_config_set(store = here::here("_targets"))
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Making a table

```{r}
lipidomics %>%
  group_by(metabolite) %>%
  summarise(across(value, list(mean = mean, sd = sd))) %>%
  mutate(across(
    where(is.numeric),
    \(x) round(x, digits = 1)
  )) %>%
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  select(Metabolite = metabolite, "Mean SD" = MeanSD)
```

## Results: basic stats table

```{r}
tar_read(table_descriptive_stats) %>%
  knitr::kable(
    caption = "The mean and standard deviation of metabolites in lipidomics dataset."
  )
```

## Plot of distribution

```{r}
ggplot(lipidomics, aes(x = value)) +
  geom_histogram() +
  facet_wrap(vars(metabolite), scales = "free") +
  theme_minimal()
```

## Results: Distribution plot

```{r}
tar_read(plot_distributions)
```

## Preparing the data

```{r}
lipidomics %>%
  count(code, metabolite) %>%
  filter(n > 1)
```

```{r}
lipidomics |>
  group_by(pick(-value)) |>
  summarise(value = mean(value), .groups = "keep") |>
  ungroup()
```

```{r}
lipidomics |>
  filter(metabolite == "Cholesterol") |>
  mutate(
    class = as.factor(class),
    value = scale(value)
  )
```

## Running multiple models

```{r}
just_cholesterol <- lipidomics |>
  filter(metabolite == "Cholesterol") |>
  preprocess()

lipidomics |>
  filter(metabolite == "Cholesterol") |>
  preprocess() |>
  fit_all_models()
```

## Running multiple metabolites

```{r}
lipidomics |>
  group_split(metabolite) |>
  map(preprocess) |>
  map(fit_all_models) |>
  list_rbind()
```

## Appendix

```{r}
tar_read(model_results) |>
    knitr::kable(caption = "Results from the analysis from all metabolites and models.")
```
